src/Entity/Chaton.php
<?php

namespace App\Entity;

use App\Repository\ChatonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatonRepository::class)
 */
class Chaton
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sterilise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Photo;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="chatons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Proprietaire::class, inversedBy="chaton_id")
     */
    private $proprietaire_id;

    public function __construct()
    {
        $this->proprietaire_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function isSterilise(): ?bool
    {
        return $this->Sterilise;
    }

    public function setSterilise(bool $Sterilise): self
    {
        $this->Sterilise = $Sterilise;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection<int, proprietaire>
     */
    public function getProprietaireId(): Collection
    {
        return $this->proprietaire_id;
    }

    public function addProprietaireId(proprietaire $proprietaireId): self
    {
        if (!$this->proprietaire_id->contains($proprietaireId)) {
            $this->proprietaire_id[] = $proprietaireId;
        }

        return $this;
    }

    public function removeProprietaireId(proprietaire $proprietaireId): self
    {
        $this->proprietaire_id->removeElement($proprietaireId);

        return $this;
    }
}

src/Form/ChatonType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Chaton;
use App\Entity\Proprietaire;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use function Symfony\Component\Translation\t;

class ChatonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Sterilise')
            ->add('Photo')
            ->add('Categorie', EntityType::class, [
                'class'=>Categorie::class,
                'choice_label'=>"titre",
                'multiple'=>false,
                'expanded'=>false
            ])
            ->add('proprietaire_id', EntityType::class, [
                'class'=>Proprietaire::class,
                'choice_label'=>"prenom",
                'label'=> "Propriétaire",
                'multiple'=>true,
                'expanded'=>true
            ])
            ->add("ok", SubmitType::class,  array(
                "label"=>"Ajouter",
                "attr"  => array(
                    'class' => 'btn btn-success',
                ),
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chaton::class,
        ]);
    }

}

src/Controller/ChatonsController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Chaton;
use App\Entity\Proprietaire;
use App\Form\CategorieSupprimerType;
use App\Form\CategorieType;
use App\Form\ChatonSupprimerType;
use App\Form\ChatonType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChatonsController extends AbstractController
{
    /**
     * @Route("/chatons/{id}", name="app_chatons")
     */
    public function index($id, ManagerRegistry $doctrine): Response
    {
        //Aller chercher les chatons dans la base
        //Donc on a besoins d'un repository
        $categorie = $doctrine->getRepository(Categorie::class)->find($id);
        //si on n'a rien trouvé -> 404
        if (!$categorie) {
            throw $this->createNotFoundException("Aucune catégorie avec l'id $id");
        }

        return $this->render('chatons/index.html.twig', [
            'categorie' => $categorie,
            'chaton' => $categorie->getChatons(),

        ]);
    }

    /**
     * @Route("/chaton/modifier/{id}", name="app_chaton_modifier")
     */
    public function modifier($id, ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $chaton = $doctrine->getRepository(Chaton::class)->find($id); // select * from chaton where id = ...

        //si l'id n'existe pas :
        if (!$chaton) {
            throw $this->createNotFoundException("Pas de chaton avec l'id $id");
        }

        //si l'id existe :
        $form = $this->createForm(ChatonType::class, $chaton);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em = $doctrine->getManager();
            //et on dit à l'entity manager de mettre le chaton en question dans la table
            $em->persist(($chaton));

            //on génère l'appel SQL (ici un update)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("chatons/modifier.html.twig",[
            "chaton"=>$chaton,
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/chaton/ajouter", name="app_chaton_ajouter")
     */
    public function ajouter(ManagerRegistry $doctrine, Request $request): Response
    {
        //Création du formulaire avant de le passer à la vue
        //Mais avant il faut créer une catégorie vide
        $chaton= new Chaton();
        //A partir de ça je crée le formulaire
        $form=$this->createForm(ChatonType::class, $chaton);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em=$doctrine->getManager();
            //et on dit à l'entity manager de mettre la catégorie en question dans la table
            $em->persist(($chaton));

            //on génère l'appel SQL (ici un insert)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("chatons/ajouter.html.twig",[
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/chaton/supprimer/{id}", name="app_chaton_supprimer")
     */
    public function supprimer($id, ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $chaton = $doctrine->getRepository(Chaton::class)->find($id); // select * from catégoire where id = ...

        //si l'id n'existe pas :
        if (!$chaton){
            throw $this->createNotFoundException("Pas de catégories avec l'id $id");
        }

        //si l'id existe :
        $form=$this->createForm(ChatonSupprimerType::class, $chaton);

        //On gère le retour du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet catégorie est rempli
            //Donc on dit a doctrine de le save dans la Bdd (on utilise un entity manager)
            $em=$doctrine->getManager();
            //et on dit à l'entity manager de mettre la catégorie en question dans la table de supprimer
            $em->remove(($chaton));

            //on génère l'appel SQL (ici un delete)
            $em->flush();

            return $this->redirectToRoute("app_categories");
        }

        return $this->render("chatons/supprimer.html.twig",[
            "chaton"=>$chaton,
            "formulaire"=>$form->createView()
        ]);

    }

}

templates/chatons/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un chaton{% endblock %}

{% block body %}
    <div class="container">
    <h1>Ajouter un chaton</h1>
    {{ form(formulaire) }}
    </div>
{% endblock %}

templates/chatons/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des chatons{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="container">
        <h1>Gestion des chatons</h1>
        <div class="row">
            {% for c in chaton %}
                <div class="col col-3">
                    <div class="card"><img src="{{ c.photo }}" alt=""
                                           class="card-img-top">
                        <div class="card-body">
                            {% if c.sterilise == 0 %}
                                <span>Je m'appelle <b>{{ c.nom }}</b> et <b>je ne suis pas stérilisé !</b></span>
                            {% elseif c.sterilise == 1%}
                                <span>Je m'appelle <b>{{ c.nom }}</b> et <b>je suis stérilisé !</b> </span>
                            {% endif %}
                            <div class="bouton-chaton">
                                <a href="{{ path("app_chaton_modifier", {"id": c.id}) }}" class="btn btn-info">modifier</a>
                                <a href="{{ path("app_chaton_supprimer", {"id": c.id}) }}" class="btn btn-danger">supprimer</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="{{ path("app_chaton_ajouter") }}" class="mt-5 btn btn-primary">Ajouter un chaton</a>
    </div>
{% endblock %}

templates/chatons/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un chaton{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier le chaton : <i><b>{{ chaton.nom }}</b></i></h1>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/chatons/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer un chaton{% endblock %}

{% block body %}
    <div class="container">
        <h1>Es-tu sur de vouloir supprimer le chaton : <i><b>{{ chaton.nom }}</b></i> ?</h1>
        {{ form(formulaire) }}
        {# je vais mettre le bouton retour #}
        <a href="{{ path("app_categories") }}" class="btn btn-success">Non</a>
    </div>
{% endblock %}